services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    restart: unless-stopped
    ports:
      - "3001:80"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - REVALIDATE_SECRET=${REVALIDATE_SECRET}
