name: CLA Assistant
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA }}
        with:
          path-to-signatures: 'signatures/cla.json'
          path-to-document: 'https://github.com/qqCMS-Org/qqCMS/blob/main/CLA.md'